// <auto-generated />
using entity_app.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace entity_app.Migrations
{
    [DbContext(typeof(EntityContext))]
    partial class EntityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("entity_app.Models.Center", b =>
                {
                    b.Property<int>("centerid")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("coordinatorid");

                    b.Property<DateTime>("created_at");

                    b.Property<DateTime>("date");

                    b.Property<string>("description");

                    b.Property<int>("duration");

                    b.Property<string>("duration_time");

                    b.Property<TimeSpan>("time");

                    b.Property<string>("title");

                    b.Property<DateTime>("updated_at");

                    b.HasKey("centerid");

                    b.HasIndex("coordinatorid");

                    b.ToTable("centers");
                });

            modelBuilder.Entity("entity_app.Models.Participant", b =>
                {
                    b.Property<int>("participantid")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("activityid");

                    b.Property<DateTime>("created_at");

                    b.Property<DateTime>("updated_at");

                    b.Property<int>("userid");

                    b.HasKey("participantid");

                    b.HasIndex("activityid");

                    b.HasIndex("userid");

                    b.ToTable("participants");
                });

            modelBuilder.Entity("entity_app.Models.User", b =>
                {
                    b.Property<int>("userid")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("created_at");

                    b.Property<string>("email");

                    b.Property<string>("first_name");

                    b.Property<string>("last_name");

                    b.Property<string>("password");

                    b.Property<DateTime>("updated_at");

                    b.HasKey("userid");

                    b.ToTable("users");
                });

            modelBuilder.Entity("entity_app.Models.Center", b =>
                {
                    b.HasOne("entity_app.Models.User", "coordinator")
                        .WithMany("activities")
                        .HasForeignKey("coordinatorid")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("entity_app.Models.Participant", b =>
                {
                    b.HasOne("entity_app.Models.Center", "activity")
                        .WithMany("participants")
                        .HasForeignKey("activityid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("entity_app.Models.User", "user")
                        .WithMany("visitants")
                        .HasForeignKey("userid")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
